### ISSUE TITLE
Multiplication and division with decimals

### ISSUE THREAD

**Issue by pil0t** [dgg/nmoneys#34]
I don't found support for multiplication and division for decimal numbers.
For example I would like to use something like var valueOfSmth = price * 1.3; where price is Money.

Is it intentionally not implemented or it is good feature to implement?

**Comment by dgg** [comment]
Hi Vlad,

First  of all is thanking you for using the library and, most importantly,
providing feedback.

You are right, there is only support for integral product and that is
intentional. Opening the door for explicit rational product might have
consequences such as "loosing" decimals when used to perform divisions.

The idea is that, for performing divisions, the .Allocate()  method is
used, which offers a "safe" way of dividing amounts.

If one is aware of the consequences the operation can have, the operation
can still be performed using the .Perform() method that allows arbitrary
unary operations on the amount, preserving the currency. Its syntax can be
further enhanced by wrapping it with an extension method.

I hope that it helps

**Comment by dgg** [comment]
Cleaning issues
